name: dconf
description: >
  dconf

version: 0.1.0
homepage: https://github.com/platelk/dconf
author: PLATEL Kevin <platel.kevin@gmail.con>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  yaml: ^2.1.15

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.5.3
